### ISSUE TITLE
QEverCloud library in Debian official repository

### ISSUE THREAD

**Issue by hosiet** [d1vanov/QEverCloud#11]
Finally QEverCloud 3.x library entered Debian official repository (https://tracker.debian.org/pkg/qevercloud). This library will be available in Debian Stretch (Debian 9), Ubuntu 17.04 and later derivatives.

Bugs may be reported to either upstream here or Debian Bug Tracking System (https://bugs.debian.org/cgi-bin/pkgreport.cgi?src=qevercloud) by users.

**Comment by d1vanov** [comment]
That's great news! Thank you a lot for all the hard work you did to make it happen!

I'll keep this issue open for a little while to commit the change to README.md informing about this great event 😃

**Comment by d1vanov** [comment]
Added the note to README.md
