### ISSUE TITLE
Add force QtWebkit / QtWebEngine options

### ISSUE THREAD

**Issue by hosiet** [d1vanov/QEverCloud#3]
Some distributions (yes, I mean debian) does not ship qt5webengine. It would be great if we have a configure-time switch to force the selection of qtwebkit / qtwebengine rather than doing wild-guess using Qt version.

This means some rewrite of `QEvercloud/cmake/modules/QEverCloudSetupQt.cmake`.

**Comment by d1vanov** [comment]
Yes, I thought about it myself already. It's possible to add such a switch, will try to do that in some nice way.

**Comment by d1vanov** [comment]
Don't you occasionally know if Debian is going to ship qt5webengine eventually? I thought in Qt 5.6 the problems with thirdparty libraries bundling were solved.

**Comment by hosiet** [comment]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=832420

We might need to track this.

**Comment by d1vanov** [comment]
I've pushed [this](https://github.com/d1vanov/QEverCloud/commit/9916f432c82c37c84f81065f9d5125c05eb49d37) commit to feature branch for now as I don't have a good testing environment in front of me at the moment. It adds "USE_QT5_WEBKIT" CMake option which can override the use of Qt5WebEngine for Qt >= 5.4. If you could help with testing, it would be much appreciated :)

**Comment by d1vanov** [comment]
Ok, that feature branch is now merged to master, I've tested it with several Qt 5.x versions, seems to work ok. Also bumped the QEverCloud version to 3.0.2.
